# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download Kernel Source from Google Drive
        run: |
          wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=19uPZidD7pAqI0rHdGWehUKiMjVDvEUup' -O kernel_source.zip
          unzip kernel_source.zip -d kernel-source

      - name: Patch NetHunter
        run: |
          cd kernel-source
          git clone https://github.com/kimocoder/kali-nethunter-kernel-patches.git
          cd kali-nethunter-kernel-patches
          chmod +x patch.sh
          ./patch.sh ../

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/${{ github.repository }}
          kernel-dir: kernel-source
          kernel-branch: main
          config: a16_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 15
          disable-lto: true
          anykernel3: true
          
